# Generated by Django 4.1 on 2022-12-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_icccomplaint_delete_userregistered'),
    ]

    operations = [
        migrations.CreateModel(
            name='acscomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='cccomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ncdcomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='seacomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sqcomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
