# Generated by Django 4.1 on 2023-01-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_acscomplaint_cccomplaint_ncdcomplaint_seacomplaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acscomplaints',
            fields=[
                ('tokenid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cccomplaints',
            fields=[
                ('tokenid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Icccomplaints',
            fields=[
                ('tokenid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ncdcomplaints',
            fields=[
                ('tokenid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Seacomplaints',
            fields=[
                ('tokenid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sqcomplaints',
            fields=[
                ('tokenid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=50)),
                ('typeofcomplaint', models.CharField(max_length=100)),
                ('complaintlevel', models.CharField(default='L1', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='acscomplaint',
        ),
        migrations.DeleteModel(
            name='cccomplaint',
        ),
        migrations.DeleteModel(
            name='icccomplaint',
        ),
        migrations.DeleteModel(
            name='ncdcomplaint',
        ),
        migrations.DeleteModel(
            name='seacomplaint',
        ),
        migrations.DeleteModel(
            name='sqcomplaint',
        ),
    ]
